/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Confession {
  'id' : ConfessionId,
  'tags' : Array<string>,
  'text' : string,
  'isHidden' : boolean,
  'timestamp' : bigint,
}
export type ConfessionId = bigint;
export interface _SERVICE {
  'claimOwnership' : ActorMethod<[], boolean>,
  'deleteConfession' : ActorMethod<[bigint], boolean>,
  'getConfessionsByTag' : ActorMethod<[string], Array<Confession>>,
  'getOwnerConfessions' : ActorMethod<[], Array<Confession>>,
  'getPublicConfessions' : ActorMethod<[], Array<Confession>>,
  'submitConfession' : ActorMethod<[string, Array<string>], bigint>,
  'toggleHideConfession' : ActorMethod<[bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];