/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : CommentId,
  'text' : string,
  'timestamp' : bigint,
  'confessionId' : ConfessionId,
}
export type CommentId = bigint;
export interface Confession {
  'id' : ConfessionId,
  'tags' : Array<string>,
  'text' : string,
  'isHidden' : boolean,
  'timestamp' : bigint,
  'commentCount' : bigint,
  'reactions' : ReactionCount,
}
export type ConfessionId = bigint;
export type Reaction = { 'Sad' : null } |
  { 'Relatable' : null } |
  { 'Funny' : null } |
  { 'Crazy' : null };
export interface ReactionCount {
  'sad' : bigint,
  'funny' : bigint,
  'crazy' : bigint,
  'relatable' : bigint,
}
export interface TagAnalytic { 'tag' : string, 'count' : bigint }
export interface _SERVICE {
  'addComment' : ActorMethod<[bigint, string], Comment>,
  'addReaction' : ActorMethod<[bigint, Reaction], ReactionCount>,
  'claimOwnership' : ActorMethod<[], boolean>,
  'deleteConfession' : ActorMethod<[bigint], boolean>,
  'getAllConfessions' : ActorMethod<[], Array<Confession>>,
  'getComments' : ActorMethod<[bigint], Array<Comment>>,
  'getConfessionOfDay' : ActorMethod<[], [] | [Confession]>,
  'getConfessionsByTag' : ActorMethod<[string], Array<Confession>>,
  'getPublicConfessions' : ActorMethod<[], Array<Confession>>,
  'getTagAnalytics' : ActorMethod<[], Array<TagAnalytic>>,
  'getTrendingConfessions' : ActorMethod<[], Array<Confession>>,
  'submitConfession' : ActorMethod<[string, Array<string>], bigint>,
  'toggleHideConfession' : ActorMethod<[bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];