/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ConfessionId = IDL.Nat;
export const Confession = IDL.Record({
  'id' : ConfessionId,
  'tags' : IDL.Vec(IDL.Text),
  'text' : IDL.Text,
  'isHidden' : IDL.Bool,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'claimOwnership' : IDL.Func([], [IDL.Bool], []),
  'deleteConfession' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getConfessionsByTag' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Confession)],
      ['query'],
    ),
  'getOwnerConfessions' : IDL.Func([], [IDL.Vec(Confession)], ['query']),
  'getPublicConfessions' : IDL.Func([], [IDL.Vec(Confession)], ['query']),
  'submitConfession' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [IDL.Nat], []),
  'toggleHideConfession' : IDL.Func([IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ConfessionId = IDL.Nat;
  const Confession = IDL.Record({
    'id' : ConfessionId,
    'tags' : IDL.Vec(IDL.Text),
    'text' : IDL.Text,
    'isHidden' : IDL.Bool,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'claimOwnership' : IDL.Func([], [IDL.Bool], []),
    'deleteConfession' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getConfessionsByTag' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Confession)],
        ['query'],
      ),
    'getOwnerConfessions' : IDL.Func([], [IDL.Vec(Confession)], ['query']),
    'getPublicConfessions' : IDL.Func([], [IDL.Vec(Confession)], ['query']),
    'submitConfession' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [IDL.Nat], []),
    'toggleHideConfession' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };