/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ReactionCount {
    sad: bigint;
    funny: bigint;
    crazy: bigint;
    relatable: bigint;
}
export type CommentId = bigint;
export interface Comment {
    id: CommentId;
    text: string;
    timestamp: bigint;
    confessionId: ConfessionId;
}
export interface Confession {
    id: ConfessionId;
    tags: Array<string>;
    text: string;
    isHidden: boolean;
    timestamp: bigint;
    commentCount: bigint;
    reactions: ReactionCount;
}
export type ConfessionId = bigint;
export interface TagAnalytic {
    tag: string;
    count: bigint;
}
export enum Reaction {
    Sad = "Sad",
    Relatable = "Relatable",
    Funny = "Funny",
    Crazy = "Crazy"
}
export interface backendInterface {
    addComment(confessionId: bigint, text: string): Promise<Comment>;
    addReaction(confessionId: bigint, reaction: Reaction): Promise<ReactionCount>;
    claimOwnership(): Promise<boolean>;
    deleteConfession(id: bigint): Promise<boolean>;
    getAllConfessions(): Promise<Array<Confession>>;
    getComments(confessionId: bigint): Promise<Array<Comment>>;
    getConfessionOfDay(): Promise<Confession | null>;
    getConfessionsByTag(tag: string): Promise<Array<Confession>>;
    getPublicConfessions(): Promise<Array<Confession>>;
    getTagAnalytics(): Promise<Array<TagAnalytic>>;
    getTrendingConfessions(): Promise<Array<Confession>>;
    submitConfession(text: string, tags: Array<string>): Promise<bigint>;
    toggleHideConfession(id: bigint): Promise<boolean>;
}
import type { Confession as _Confession, Reaction as _Reaction } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addComment(arg0: bigint, arg1: string): Promise<Comment> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async addReaction(arg0: bigint, arg1: Reaction): Promise<ReactionCount> {
        if (this.processError) {
            try {
                const result = await this.actor.addReaction(arg0, to_candid_Reaction_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReaction(arg0, to_candid_Reaction_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async claimOwnership(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.claimOwnership();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimOwnership();
            return result;
        }
    }
    async deleteConfession(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteConfession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteConfession(arg0);
            return result;
        }
    }
    async getAllConfessions(): Promise<Array<Confession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllConfessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllConfessions();
            return result;
        }
    }
    async getComments(arg0: bigint): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0);
            return result;
        }
    }
    async getConfessionOfDay(): Promise<Confession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getConfessionOfDay();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConfessionOfDay();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConfessionsByTag(arg0: string): Promise<Array<Confession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConfessionsByTag(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConfessionsByTag(arg0);
            return result;
        }
    }
    async getPublicConfessions(): Promise<Array<Confession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicConfessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicConfessions();
            return result;
        }
    }
    async getTagAnalytics(): Promise<Array<TagAnalytic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTagAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTagAnalytics();
            return result;
        }
    }
    async getTrendingConfessions(): Promise<Array<Confession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingConfessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingConfessions();
            return result;
        }
    }
    async submitConfession(arg0: string, arg1: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitConfession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitConfession(arg0, arg1);
            return result;
        }
    }
    async toggleHideConfession(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleHideConfession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleHideConfession(arg0);
            return result;
        }
    }
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Confession]): Confession | null {
    return value.length === 0 ? null : value[0];
}
function to_candid_Reaction_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Reaction): _Reaction {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Reaction): {
    Sad: null;
} | {
    Relatable: null;
} | {
    Funny: null;
} | {
    Crazy: null;
} {
    return value == Reaction.Sad ? {
        Sad: null
    } : value == Reaction.Relatable ? {
        Relatable: null
    } : value == Reaction.Funny ? {
        Funny: null
    } : value == Reaction.Crazy ? {
        Crazy: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
